[package]
name = "wasm-gravity"
version = "0.1.4"
edition = "2024"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]

[lib]
name = "gravity"

[[bin]]
name = "gravity"
path = "src/main.rs"

[features]
default = ["desktop"]
desktop = ["wgame/desktop"]
web = ["wgame/web"]

[dependencies]
phy = { path = "phy" }
rand = { version = "0.10.2", default-features = false, features = ["std"] }
wgame = { path = "wgame/wgame", default-features = false, features = [
    "shapes",
    "typography",
] }
