[package]
name = "wasm-gravity"
version = "0.1.4"
edition = "2024"
authors = ["Alexey Gerasev <alexey.gerasev@gmail.com>"]

[lib]
name = "gravity"

[[bin]]
name = "gravity"
path = "src/main.rs"

[features]
default = ["desktop"]
desktop = ["wgame/desktop", "wgame-egui/desktop"]
web = ["wgame/web", "wgame-egui/web"]

[dependencies]
phy = { path = "phy" }
rand = { version = "0.10.2", default-features = false, features = ["std"] }
wgame = { path = "wgame/wgame", default-features = false, features = [
    "shapes",
] }

wgame-egui = { path = "wgame/wgame-egui", default-features = false }
